/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_wang_testapp_ccp_NativeTest */

#ifndef _Included_com_wang_testapp_ccp_NativeTest
#define _Included_com_wang_testapp_ccp_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wang_testapp_ccp_NativeTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wang_testapp_ccp_NativeTest_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_wang_testapp_ccp_NativeTest
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_wang_testapp_ccp_NativeTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
